language: python
cache: pip
python:
  - "3.7"
install:
  - pip install -r requirements.txt --quiet
  - pip install coverage coveralls --quiet
script:
  - coverage run --source=snippets -m unittest tests
  - coveralls
