language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt --quiet
  - pip install corvage --quiet
script:
  - corvage -m unittest tests
  - corvage report
  - corvage html