language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt --quiet
  - pip install coverage --quiet
script:
  - coverage -m unittest tests
  - coverage report
  - coverage html